// Template tags: 
// Default - Name of output class.
// Default - Name of current group.
// <sprite_name> - Name of each sprite.
// <sprite_hash_name> - Hash name of each sprite.


using Microsoft.Xna.Framework.Content;
using Monofoxe.Engine;
using Monofoxe.Engine.Drawing;
using System.Collections.Generic;
using Monofoxe.Engine.Resources;

// NOTE: This class is automatically generated by
// Monofoxe. See .cstemplate file.

namespace Resources.Sprites
{
	public class Default : ResourceBox<Sprite>
	{
		public override string Name => "DefaultSprites";
		
		private ContentManager _content = new ContentManager(GameMgr.Game.Services);
		
		public override void Load()
		{
			if (Loaded)
			{
				return;
			}
			Loaded = true;
			var graphicsPath = AssetMgr.ContentDir + '/' + AssetMgr.GraphicsDir +  "/Default";
			var sprites = _content.Load<Dictionary<string, Sprite>>(graphicsPath);
			
			#region Sprite constructors.
			
			AddResource("Monofoxe", sprites["monofoxe"]);
			
			#endregion Sprite constructors.
		}
		
		public override void Unload()
		{
			if (!Loaded)
			{
				return;
			}
			Loaded = false;
			_content.Unload();
		}
	}
}
